### ISSUE TITLE
Remove phreatophytes

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/DIT_CRSS_DB#3]
Keep DIT in line with CRSS:  https://github.com/BoulderCodeHub/crss.v5/issues/75

**Comment by khumphreysBOR** [comment]
Cannot currently delete Aggregate Diversion Sites in the DIT. As a stopgap until this bug is fixed by CADSWES, all phreatophyte water user demand (listed below) has been set to 0. 

- PHREATOPHYTES, DAVIS TO PARKER=Phreatophytes:Phreatophytes
- PHREATOPHYTES, PARKER TO IMPERIAL=NativeVegetation:NativeVegetation
- PHREATOPHYTES, IMPERIAL TO NORTHERLY INTERNATIONAL BOUNDARY=PhreatophytesImperialToNIB:PhreatophytesImperialToNIB

**Comment by khumphreysBOR** [comment]
Added to DIT in[ 2.9.5](https://github.com/usbr/DIT_CRSS_DB/commit/2e225be405eafd305ab34d68687714c684c0274c)

Updated in [CRSSv6_9047](https://github.com/BoulderCodeHub/crss.v5/pull/103)

**Comment by khumphreysBOR** [comment]
PHREATOPHYTES, DAVIS TO PARKER, PHREATOPHYTES, PARKER TO IMPERIAL, PHREATOPHYTES, IMPERIAL TO NORTHERLY INTERNATIONAL BOUNDARY deleted in 2.9.7

[Verification results](https://github.com/usbr/DIT_CRSS_DB/issues/2).
